feat: allow patching the Dockerfile per MFE
overhangio/tutor-mfe pull request #134
Opened 2023-06-21 14:04 UTC by arbrandes

This should allow managing individual MFE node_modules (such as installing custom dependencies for l10n purposes) without having to fork the corresponding upstream codebases.

2023-06-21 14:06 UTC, arbrandes commented
This should help with custom localization scenarios such as [the one shared by Dimitris](https://discuss.openedx.org/t/problems-applying-customised-mfe-libraries-eg-frontend-platform-to-a-production-open-edx-platform-using-tutor-local/8691/15?u=arbrandes).

@regisb, thoughts?

2023-06-22 07:20 UTC, regisb requested changes
Excellent! Can you please add a changelog entry? I think we should also add some information to the README in the "Customising MFEs" section.

2023-06-23 13:34 UTC, arbrandes commented
Done!

2023-06-23 13:48 UTC, regisb approved these changes
grand!

2023-06-23 13:48 UTC, merged