feat: allow to patch MFE caddyfile
overhangio/tutor-mfe pull request #148
Opened 2023-09-13 12:31 UTC by snglth

Comes in hand if you want to add basicauth

2023-09-13 13:42 UTC, regisb requested changes
Thanks for the PR! Can you please add a changelog entry with `scriv create`?

2023-09-13 13:42 UTC, regisb commented on tutormfe/templates/mfe/apps/mfe/Caddyfile
> +    {{ patch("caddyfile-mfe") | indent(4) }}
Please rename to "mfe-caddyfile".

2023-09-14 09:53 UTC, snglth commented on tutormfe/templates/mfe/apps/mfe/Caddyfile
> +    {{ patch("caddyfile-mfe") | indent(4) }}
Done

2023-09-14 09:54 UTC, snglth commented
Changelog entry created. Is it possible to also get it into 15.x version of tutor-mfe?

2023-09-21 10:05 UTC, regisb approved these changes
LGTM! FYI @arbrandes I let you check out this PR and merge/comment.

2023-09-21 10:06 UTC, regisb commented
> Changelog entry created. Is it possible to also get it into 15.x version of tutor-mfe?

Unfortunately no, as we do not maintain older releases of Tutor and its plugins. You will have to maintain a temporary fork of tutor v15 yourself.

2023-09-22 13:41 UTC, arbrandes approved these changes
LGTM!

2023-09-22 13:41 UTC, merged