Fix: MFE_HOST check with the new CONFIG_LOADED action
overhangio/tutor-mfe pull request #150
Opened 2023-10-01 07:03 UTC by CodeWithEmad

As a part of https://github.com/overhangio/tutor/issues/557, we should warn the users if they're not following the apps.LMS_HOST pattern for the MFE_HOST. This will introduce a new check to see if the MFE_HOST is a subdomain of LMS_HOST or not using the new CONFIG_LOADED action.

2023-10-02 04:41 UTC, regisb commented on setup.py
> +    install_requires=["tutor>=16.1.2,<17.0.0"],
Note to self: this PR is dependent on [this one #901](https://github.com/overhangio/tutor/pull/901) and will require a new release of tutor.

2023-10-02 12:35 UTC, regisb requested changes
LGTM! Can you please just add a changelog entry with `scriv create`?

2023-10-02 13:58 UTC, CodeWithEmad commented
> LGTM! Can you please just add a changelog entry with `scriv create`?

Done.

2023-10-02 15:00 UTC, regisb approved these changes
lgtm!

2023-10-06 14:28 UTC, arbrandes approved these changes
No objections, thanks!

2023-10-06 14:29 UTC, merged