docs: document mfe patches catalog
overhangio/tutor-mfe pull request #177
Opened 2023-12-12 08:28 UTC by Danyal-Faheem

**Changes**

- Added a catalog which includes every patch available for tutor-mfe in the README.
- Also included a one liner description of each patch for users to understand.

Fixes this [issue.](https://github.com/overhangio/tutor-mfe/issues/168)

2023-12-12 08:50 UTC, regisb requested changes
This is excellent work! I only have a few minor comments.

2023-12-12 08:50 UTC, regisb commented on README.rst
> +Add any additional configurations to be added at the end of the development webpack config file in Javascript format.
"Add" and "additional" are redundant. I suggest you replace "Add any additional XYZ" by "Add any XYZ" everywhere.

2023-12-12 08:50 UTC, regisb commented on README.rst
> +Example: ``mfe-dockerfile-pre-npm-install-learning`` Will only apply any instructions specified for the learning mfe.
Will -> will

2023-12-12 08:50 UTC, regisb commented on README.rst
> +Add any additional instructions for before the build step initializes for a specific mfe. Add the exact mfe name at the end to only change instructions for that mfe. For an example on the usage of th
a specific mfe -> a specific MFE
for that mfe -> for that MFE

(same for other occurrences of "mfe" in the document)

2023-12-12 08:50 UTC, regisb commented on changelog.d/20231212_131405_danyal.faheem_document_mfe_patches_catalog.md
> +- [Improvement] Added a patch catalog for tutor-mfe which includes a one liner description of every patch available. (by @Danyal-Faheem)
No need to add a changelog entry, as this change is not affecting the end user.

2023-12-12 09:54 UTC, regisb commented
@arbrandes what do you think?

2023-12-15 16:21 UTC, arbrandes approved these changes
This is fantastic!  Thanks!

2023-12-18 08:31 UTC, merged