fix: render mfe-ports for  unmounted mfes when these exist
overhangio/tutor-mfe pull request #241
Opened 2024-12-14 06:30 UTC by hinakhadim

### Description
The issue occurs when all MFEs (Micro Frontends) are mounted, and the `ports` section in the Docker configuration is left empty, leading to a syntax error in the generated Dockerfile. Specifically, the `ports:` line becomes invalid as another key follows it (`auth:`) without any content. In the `tutor dev` context, the issue occurs because developers mount MFEs for testing purposes. It won't reproduce for `tutor local`.

```
...

mfe:
    ports:
auth:
   ....
```

### How to Reproduce
- Clone all MFEs (`authn, account, communications, course-authoring, discussions, gradebook, learner-dashboard, learning, ora-grading, profile`)
- Run `tutor mounts add $(pwd)/frontend-app-*` where `*` represents all MFEs name one by one
- `tutor config save`
- `tutor dev start` OR directly check the `mfe-ports` section in `tutor-env/env/dev/docker-compose.yml` 

### What this PR does
This PR resolves the issue by implementing logic to first check if any unmounted MFEs exist. If unmounted MFEs are found, their corresponding ports are rendered in the ports: section. This ensures that the Docker configuration is generated correctly and avoids errors caused by leaving the `ports:` section empty.

### TestCases:
- [x] If any unmounted MFE exists, its corresponding port should be rendered under the `mfe: ports:` section.
```
...

mfe:
    ports:
        - 1997:8002 # account
        - 1984:8002 # communications

authn:
    image: ...
...           
```
- [x] If no unmounted MFEs exist, the `mfe: ports:` section should be excluded entirely from the generated output.
```
...
#There should be no section of mfe->ports

authn:
     image: ....
...          
```

Closes https://github.com/overhangio/tutor/issues/1167

2024-12-16 11:08 UTC, regisb requested changes
This solution is way better than the one I initially suggested. Please just add a changelog entry and add "close #242" to your commit message.

2024-12-16 11:08 UTC, regisb commented on tutormfe/patches/local-docker-compose-dev-services
> +{% if unmounted_mfes|length > 0 %}
nit: `{% if unmounted_mfes|length > 0 %}`

2024-12-16 11:08 UTC, regisb commented on tutormfe/patches/local-docker-compose-dev-services
> +{%- for app_name, app in iter_mfes() %}
Could we simplify this declaration with the following?

```
{%- set unmounted_mfes = [(app_name, app) for app_name, app in iter_mfes() if not list(iter_mounts(MOUNTS, app_name))] %}
```

2024-12-31 13:39 UTC, DawoudSheraz commented on tutormfe/patches/local-docker-compose-dev-services
> +       {%- set _ = unmounted_mfes.append((app_name, app)) %}
shouldn't append be enough by itself? Is it necessary to set the output to _?

2025-01-13 09:03 UTC, hinakhadim commented on tutormfe/patches/local-docker-compose-dev-services
> +{%- for app_name, app in iter_mfes() %}
I've tried to applied using the below code.
```python
def get_unmounted_mfes() -> list:
    unmounted_mfes = []
    def append_to_unmounted_mfes(mounts: list[str], app_name:str, app: MFE_ATTRS_TYPE):
        if not mounts:
            unmounted_mfes.append((app_name, app))

        return unmounted_mfes
    return append_to_unmounted_mfes


tutor_hooks.Filters.ENV_TEMPLATE_VARIABLES.add_items(
    [
        ...
        ("get_unmounted_mfes", get_unmounted_mfes()),
    ]
)
```

That leads us to this template:
```
{%- set unmounted_mfes = [] %}

{%- for app_name, app in iter_mfes() %}
{%- set mounts = iter_mounts(MOUNTS, app_name)|list %}
{%- set unmounted_mfes = get_unmounted_mfes(mounts, app_name, app) %}  ---> here I add this line
{%- if mounts %}
{{ app_name }}: # Work on this MFE for development
...
{%- endif %}
{%- endfor %}



{% if unmounted_mfes|length > 0 %}
mfe:
   ports:
       {%- for app_name, app in unmounted_mfes %}
       - {{ app["port"] }}:8002 # {{ app_name }}
       {%- endfor %}
{% endif %}
```

2025-01-13 09:09 UTC, hinakhadim commented on tutormfe/patches/local-docker-compose-dev-services
> +       {%- set _ = unmounted_mfes.append((app_name, app)) %}
The `set _` is necessary. Jinja does not support direct in-place modifications like Python does (list.append()), so you need to reassign the list with the new value.
https://stackoverflow.com/a/66019113

2025-01-13 09:13 UTC, hinakhadim commented on tutormfe/patches/local-docker-compose-dev-services
> +{%- for app_name, app in iter_mfes() %}
I have re-arranged the code in the patch.

2025-01-14 16:02 UTC, regisb commented on tutormfe/patches/local-docker-compose-dev-services
> +{%- for app_name, app in iter_mfes() %}
I'm not a big fan of this pattern, as it moves too much declarative code to the Jinja templates. This is not a great practice. Instead, I suggest:

```
def get_unmounted_mfes(mounts):
    unmounted_mfes = []   
     for mfe in ...:
        if ...:
            unmounted_mfes.append(mfe)
    return unmounted_mfes

tutor_hooks.Filters.ENV_TEMPLATE_VARIABLES.add_item(
        ("get_unmounted_mfes", get_unmounted_mfes),
)
```

and then in the templates:

    {%- set unmounted_mfes = get_unmounted_mfes(MOUNTS) %}

2025-01-21 09:12 UTC, regisb commented on tutormfe/patches/local-docker-compose-dev-services
> +{%- for app_name, app in iter_mfes() %}
@hinakhadim did you consider my suggestion above?

2025-01-21 09:15 UTC, hinakhadim commented on tutormfe/patches/local-docker-compose-dev-services
> +{%- for app_name, app in iter_mfes() %}
I missed this message. I'll try with the suggested one. Thanks

2025-02-03 12:19 UTC, DawoudSheraz commented on tutormfe/patches/local-docker-compose-dev-services
> +{% endif %}
nit: missing end of file line.

2025-02-03 12:19 UTC, DawoudSheraz reviewed
Please add a changelog entry

2025-02-27 08:05 UTC, DawoudSheraz approved these changes
I did not test it locally but the code looks good. Nice re-organization @ahmed-arb

2025-02-28 14:24 UTC, DawoudSheraz commented
@CodeWithEmad FYI as this fixes https://github.com/overhangio/tutor-mfe/issues/242.

2025-02-28 15:09 UTC, CodeWithEmad commented
Great work, folks 🤘🏼

2025-03-05 15:04 UTC, arbrandes approved these changes
Looks great, thanks!

2025-03-11 09:36 UTC, merged