Added MFE service (patch nginx-extra)
overhangio/tutor-mfe pull request #7
Opened 2021-07-04 22:00 UTC by insad

Added MFE service in patch nginx-extra, so a reverse proxy has access to the micro frontends on {{ MFE_HOST }}

2021-07-05 07:52 UTC, regisb commented on tutormfe/patches/nginx-extra
> +    proxy_pass http://mfe-backend;
Please fix indentation.

2021-07-05 07:56 UTC, regisb requested changes
I think that we should switch the proxy in the main Caddyfile configuration, such as traffic is always redirected to nginx, and no longer to the mfe container, even when not running a proxy on the host.

To clarify, in the absence of web proxy on the host, traffic is transferred as follows:

    Caddy -> MFE container (Caddy service)

I think that it should become:

    Caddy -> Nginx container -> MFE container (Caddy service)

This approach would be more consistent with the situation when Caddy is disabled.

2021-08-30 12:59 UTC, regisb commented
@insad did you understand my last comment about adding a Caddy proxy configuration? If yes, do you have the time to take this on? If not I can do it.

2021-08-30 15:18 UTC, insad commented
Please can you do it, no time at the moment here. Besides I don't have a dev setup at hand for testing.

2021-09-02 11:49 UTC, regisb commented
Closed in favour of #8.

2021-09-02 11:49 UTC, closed without merging